(function () {
  "use strict";

  window.GubotCatalogSpecifications = {
    models: {
      "GBT-SB6900-E-ECO": {
        status: "complete",
        locales: {
          zh: [
            ["产品名称", "电加热汽车喷烤漆房"],
            ["型号", "GBT-SB6900-E-ECO"],
            ["内部尺寸", "6900 × 3900 × 2600 mm（长 × 宽 × 高）"],
            ["外部尺寸", "7000 × 5000 × 3250 mm（长 × 宽 × 高）"],
            ["房体结构", "50 mm EPS保温复合墙板，双面采用0.4 mm彩涂钢板，密度12 kg/m³。顶板采用标准化设备压制成型的0.7 mm镀锌板。"],
            ["底台", "300 mm地上式排风底台，采用镀锌板折弯制作；配置三排2.3 mm花纹钢板和两排4 × 30#镀锌钢格栅，支撑件采用镀锌板折弯制作。"],
            ["正面大门", "一套三扇式钣金大门，厚度50 mm，内部填充EPS，配置铝合金框观察窗。门体尺寸：3000 × 2500 mm（宽 × 高），采用5 mm钢化玻璃。"],
            ["工作门", "一扇工作门，尺寸700 × 1800 mm（宽 × 高），配置压力锁及铝合金框观察窗，采用5 mm钢化玻璃。"],
            ["静压室", "采用镀锌折弯加强筋及支撑框架，房体顶板兼作静压室顶板；过滤棉托架连接件采用0.6 mm镀锌板折弯制作。"],
            ["送风系统", "两台YDW 3 kW专用送风机，Tianyi品牌或同等品牌；单台风量10,000 m³/h。"],
            ["排风系统", "一台YDW 4 kW专用排风机，江苏恒康或同等品牌；风量12,500 m³/h。"],
            ["排风管道", "标准配置包含两节直管和一个弯头。"],
            ["照明系统", "房体两侧上部LED照明。灯箱框架采用0.6 mm镀锌板制作并经喷粉处理；数量：8组 × 4支，共32支24 W LED灯管。"],
            ["加热系统", "八组外置固定式红外线加热装置，每组3 kW，总加热功率24 kW；房体两侧各四组。"],
            ["过滤系统", "进风初效过滤器可捕集大于10 µm的颗粒；顶部SF-700G高效过滤棉可捕集大于4 µm的颗粒，捕集率不低于99%；底部采用中效玻璃纤维过滤棉。"],
            ["电气控制", "采用正泰（CHINT）或同等品牌电气控制元件。主回路设有漏电、缺相、短路及过载保护，并带定时功能；温度可调，配置超温报警。"],
            ["电源要求", "380 V / 220 V，三相四线，50 Hz；总功率约35 kW。"]
          ],
          en: [
            ["Product", "Electric Heating Automotive Spray / Baking Paint Booth"],
            ["Model", "GBT-SB6900-E-ECO"],
            ["Internal size", "6900 × 3900 × 2600 mm (L × W × H)"],
            ["External size", "7000 × 5000 × 3250 mm (L × W × H)"],
            ["Booth body", "50 mm EPS insulated composite wall panels with 0.4 mm color-coated steel sheets on both sides, density 12 kg/m³. Roof panels are 0.7 mm galvanized pressed panels formed by standardized equipment."],
            ["Base platform", "300 mm above-ground exhaust base made from bent galvanized sheet, with three rows of 2.3 mm checker plate and two rows of 4 × 30# galvanized floor grating. Supports are made from bent galvanized sheet."],
            ["Front door", "One set of three-leaf sheet-metal main door, 50 mm thick, with EPS infill and aluminum-alloy framed viewing windows. Door size: 3000 × 2500 mm (W × H), with 5 mm tempered glass."],
            ["Service door", "One service door, 700 × 1800 mm (W × H), with pressure lock and aluminum-alloy framed viewing window using 5 mm tempered glass."],
            ["Plenum chamber", "Galvanized folded reinforcing ribs with support frame. The booth roof panel is used as the top panel. Filter-holder connectors are made from 0.6 mm bent galvanized sheet."],
            ["Air supply system", "Two YDW 3 kW dedicated supply fans, Tianyi brand or equivalent, air volume 10,000 m³/h per fan."],
            ["Exhaust system", "One YDW 4 kW dedicated exhaust fan, Jiangsu Hengkang or equivalent, air volume 12,500 m³/h."],
            ["Exhaust duct", "Two straight ducts and one elbow are included in the standard configuration."],
            ["Lighting system", "Upper LED lighting on both sides. Powder-coated 0.6 mm galvanized light-box frames. Quantity: 8 sets × 4 tubes = 32 pcs 24 W LED tubes."],
            ["Heating system", "Eight externally mounted fixed infrared heating sets, 3 kW per set, total heating power 24 kW; four sets on each side."],
            ["Filter system", "Primary inlet filter captures particles larger than 10 µm. Top SF-700G high-efficiency filter cotton captures particles larger than 4 µm with a capture rate of at least 99%. Bottom medium-efficiency fiberglass filter cotton."],
            ["Electric control", "CHINT or equivalent electrical controller. Main circuit includes leakage, phase-loss, short-circuit, timing and overload protection. Adjustable temperature control with over-temperature alarm."],
            ["Power requirement", "380 V / 220 V, 3 phase 4 wire, 50 Hz; total power approx. 35 kW."]
          ],
          fr: [
            ["Produit", "Cabine de peinture et de séchage automobile à chauffage électrique"],
            ["Modèle", "GBT-SB6900-E-ECO"],
            ["Dimensions intérieures", "6900 × 3900 × 2600 mm (L × l × H)"],
            ["Dimensions extérieures", "7000 × 5000 × 3250 mm (L × l × H)"],
            ["Structure de la cabine", "Parois en panneaux composites isolants en EPS de 50 mm, avec tôle d'acier prélaquée de 0,4 mm sur les deux faces, densité 12 kg/m³. Panneaux de toiture en tôle galvanisée emboutie de 0,7 mm, formés par un équipement standardisé."],
            ["Soubassement", "Soubassement d'extraction hors sol de 300 mm, réalisé en tôle galvanisée pliée, avec trois rangées de tôle antidérapante de 2,3 mm et deux rangées de caillebotis galvanisé 4 × 30#. Supports en tôle galvanisée pliée."],
            ["Porte frontale", "Un ensemble de porte principale en tôle à trois vantaux, épaisseur 50 mm, avec remplissage EPS et fenêtres en verre trempé encadrées d'aluminium. Dimensions de la porte : 3000 × 2500 mm (l × H), verre trempé de 5 mm."],
            ["Porte de service", "Une porte de service de 700 × 1800 mm (l × H), avec serrure à pression et fenêtre encadrée d'aluminium équipée d'un verre trempé de 5 mm."],
            ["Plénum", "Nervures de renfort en tôle galvanisée pliée avec châssis de support. Le panneau de toiture de la cabine sert de panneau supérieur. Les supports de filtres sont réalisés en tôle galvanisée pliée de 0,6 mm."],
            ["Système de soufflage d'air", "Deux ventilateurs de soufflage dédiés YDW de 3 kW, marque Tianyi ou équivalent, débit d'air de 10 000 m³/h par ventilateur."],
            ["Système d'extraction", "Un ventilateur d'extraction dédié YDW de 4 kW, Jiangsu Hengkang ou équivalent, débit d'air de 12 500 m³/h."],
            ["Conduit d'extraction", "La configuration standard comprend deux conduits droits et un coude."],
            ["Système d'éclairage", "Éclairage LED supérieur des deux côtés. Cadres des caissons lumineux en tôle galvanisée de 0,6 mm avec revêtement en poudre. Quantité : 8 ensembles × 4 tubes = 32 tubes LED de 24 W."],
            ["Système de chauffage", "Huit ensembles fixes de chauffage infrarouge montés à l'extérieur, 3 kW par ensemble, puissance thermique totale de 24 kW ; quatre ensembles de chaque côté."],
            ["Système de filtration", "Préfiltre d'entrée pour les particules supérieures à 10 µm. Filtre supérieur haute efficacité SF-700G pour les particules supérieures à 4 µm, avec un taux de capture ≥99 %. Filtre inférieur en fibre de verre à efficacité moyenne."],
            ["Commande électrique", "Commande électrique avec composants CHINT ou équivalents. Le circuit principal comprend les protections contre les fuites, la perte de phase, les courts-circuits, la temporisation et les surcharges. Température réglable avec alarme de surchauffe."],
            ["Alimentation électrique", "380 V / 220 V, 3 phases, 4 fils, 50 Hz ; puissance totale d'environ 35 kW."]
          ],
          es: [
            ["Producto", "Cabina de pintura y secado para automóviles con calefacción eléctrica"],
            ["Modelo", "GBT-SB6900-E-ECO"],
            ["Dimensiones internas", "6900 × 3900 × 2600 mm (L × An × Al)"],
            ["Dimensiones externas", "7000 × 5000 × 3250 mm (L × An × Al)"],
            ["Estructura de la cabina", "Paneles de pared compuestos aislantes de EPS de 50 mm, con chapa de acero prepintada de 0,4 mm en ambos lados, densidad 12 kg/m³. Paneles de techo de chapa galvanizada prensada de 0,7 mm, conformados con equipo estandarizado."],
            ["Base de la cabina", "Base de extracción elevada de 300 mm, fabricada en chapa galvanizada plegada, con tres filas de chapa estriada de 2,3 mm y dos filas de rejilla galvanizada de 4 × 30#. Soportes fabricados en chapa galvanizada plegada."],
            ["Puerta frontal", "Un juego de puerta principal de chapa metálica de tres hojas, 50 mm de espesor, con relleno de EPS y ventanas de vidrio templado con marco de aluminio. Tamaño de la puerta: 3000 × 2500 mm (An × Al), vidrio templado de 5 mm."],
            ["Puerta de servicio", "Una puerta de servicio de 700 × 1800 mm (An × Al), con cerradura de presión y ventana con marco de aluminio y vidrio templado de 5 mm."],
            ["Cámara plenum", "Nervios de refuerzo de chapa galvanizada plegada con bastidor de soporte. El panel del techo de la cabina se utiliza como panel superior. Los soportes de los filtros son de chapa galvanizada plegada de 0,6 mm."],
            ["Sistema de impulsión de aire", "Dos ventiladores de impulsión YDW de 3 kW, marca Tianyi o equivalente, caudal de aire de 10.000 m³/h por ventilador."],
            ["Sistema de extracción", "Un ventilador de extracción YDW de 4 kW, Jiangsu Hengkang o equivalente, caudal de aire de 12.500 m³/h."],
            ["Conducto de extracción", "La configuración estándar incluye dos conductos rectos y un codo."],
            ["Sistema de iluminación", "Iluminación LED superior en ambos lados. Marcos de las cajas de luz de chapa galvanizada de 0,6 mm con recubrimiento en polvo. Cantidad: 8 juegos × 4 tubos = 32 tubos LED de 24 W."],
            ["Sistema de calefacción", "Ocho juegos fijos de calefacción por infrarrojos montados externamente, 3 kW por juego, potencia térmica total de 24 kW; cuatro juegos en cada lado."],
            ["Sistema de filtración", "Prefiltro de entrada para partículas superiores a 10 µm. Filtro superior SF-700G de alta eficiencia para partículas superiores a 4 µm, con eficiencia de captura ≥99 %. Filtro inferior de fibra de vidrio de eficiencia media."],
            ["Control eléctrico", "Controlador eléctrico con componentes CHINT o equivalentes. El circuito principal incluye protección contra fugas, pérdida de fase, cortocircuito, temporización y sobrecarga. Temperatura ajustable con alarma de sobretemperatura."],
            ["Alimentación eléctrica", "380 V / 220 V, 3 fases, 4 hilos, 50 Hz; potencia total aproximada de 35 kW."]
          ],
          it: [
            ["Prodotto", "Cabina di verniciatura e cottura per auto con riscaldamento elettrico"],
            ["Modello", "GBT-SB6900-E-ECO"],
            ["Dimensioni interne", "6900 × 3900 × 2600 mm (L × P × H)"],
            ["Dimensioni esterne", "7000 × 5000 × 3250 mm (L × P × H)"],
            ["Struttura cabina", "Pareti della cabina in pannelli compositi isolanti EPS da 50 mm, con lamiera d'acciaio preverniciata da 0,4 mm su entrambi i lati, densità 12 kg/m³. Pannelli del tetto in lamiera zincata pressata da 0,7 mm, formati con attrezzatura standardizzata."],
            ["Basamento", "Basamento di aspirazione fuori terra alto 300 mm, realizzato in lamiera zincata piegata, con tre file di lamiera mandorlata da 2,3 mm e due file di grigliato zincato 4 × 30#. Supporti in lamiera zincata piegata."],
            ["Porta frontale", "Un set di porta principale in lamiera a tre ante, spessore 50 mm, con riempimento EPS e finestre con vetro temperato incorniciate in alluminio. Dimensioni porta: 3000 × 2500 mm (L × H), vetro temperato da 5 mm."],
            ["Porta di servizio", "Una porta di servizio da 700 × 1800 mm (L × H), con serratura a pressione e finestra con telaio in alluminio e vetro temperato da 5 mm."],
            ["Camera di pressurizzazione", "Nervature di rinforzo in lamiera zincata piegata con telaio di supporto. Il pannello del tetto della cabina funge da pannello superiore. I supporti dei filtri sono in lamiera zincata piegata da 0,6 mm."],
            ["Sistema di mandata aria", "Due ventilatori di mandata dedicati YDW da 3 kW, marca Tianyi o equivalente, portata d'aria 10.000 m³/h per ventilatore."],
            ["Sistema di estrazione", "Un ventilatore di estrazione dedicato YDW da 4 kW, Jiangsu Hengkang o equivalente, portata d'aria 12.500 m³/h."],
            ["Condotto di scarico", "La configurazione standard include due condotti diritti e una curva."],
            ["Sistema di illuminazione", "Illuminazione LED superiore su entrambi i lati. Telai delle plafoniere in lamiera zincata da 0,6 mm verniciata a polvere. Quantità: 8 gruppi × 4 tubi = 32 tubi LED da 24 W."],
            ["Sistema di riscaldamento", "Otto gruppi fissi di riscaldamento a infrarossi montati esternamente, 3 kW per gruppo, potenza termica totale 24 kW; quattro gruppi per lato."],
            ["Sistema di filtrazione", "Prefiltro di ingresso per particelle superiori a 10 µm. Filtro superiore ad alta efficienza SF-700G per particelle superiori a 4 µm, efficienza di cattura ≥99%. Filtro inferiore in fibra di vetro a media efficienza."],
            ["Quadro elettrico", "Quadro elettrico con componenti CHINT o equivalenti. Il circuito principale comprende protezione da dispersione, mancanza di fase, cortocircuito, temporizzazione e sovraccarico. Temperatura regolabile con allarme di sovratemperatura."],
            ["Alimentazione elettrica", "380 V / 220 V, 3 fasi, 4 fili, 50 Hz; potenza totale circa 35 kW."]
          ],
          de: [
            ["Produkt", "Elektrisch beheizte Fahrzeug-Lackier- und Trockenkabine"],
            ["Modell", "GBT-SB6900-E-ECO"],
            ["Innenabmessungen", "6900 × 3900 × 2600 mm (L × B × H)"],
            ["Außenabmessungen", "7000 × 5000 × 3250 mm (L × B × H)"],
            ["Kabinenaufbau", "50 mm starke EPS-Wärmedämmverbundpaneele mit beidseitig 0,4 mm starkem, farbbeschichtetem Stahlblech; Dichte 12 kg/m³. Die Dachpaneele bestehen aus 0,7 mm starkem, verzinktem Pressblech und werden auf standardisierten Anlagen geformt."],
            ["Unterbau", "300 mm hoher, oberirdischer Abluftunterbau aus gekantetem verzinktem Stahlblech, ausgestattet mit drei Reihen 2,3 mm starkem Riffelblech und zwei Reihen verzinktem Bodengitterrost 4 × 30#. Die Stützelemente bestehen aus gekantetem verzinktem Stahlblech."],
            ["Fronttor", "Ein dreiflügeliges Haupttor aus Stahlblech, 50 mm stark, mit EPS-Füllung und Sichtfenstern in Aluminiumrahmen. Torabmessungen: 3000 × 2500 mm (B × H), mit 5 mm starkem Einscheiben-Sicherheitsglas."],
            ["Servicetür", "Eine Servicetür mit den Abmessungen 700 × 1800 mm (B × H), ausgestattet mit Druckverschluss und Sichtfenster im Aluminiumrahmen mit 5 mm starkem Einscheiben-Sicherheitsglas."],
            ["Druckkammer", "Verstärkungsrippen und Tragrahmen aus gekantetem verzinktem Stahlblech. Das Kabinendachpaneel dient gleichzeitig als obere Abdeckung. Die Verbindungselemente der Filterhalter bestehen aus 0,6 mm starkem, gekantetem verzinktem Stahlblech."],
            ["Zuluftsystem", "Zwei YDW-Spezial-Zuluftventilatoren mit jeweils 3 kW, Fabrikat Tianyi oder gleichwertig; Luftleistung je Ventilator 10.000 m³/h."],
            ["Abluftsystem", "Ein YDW-Spezial-Abluftventilator mit 4 kW, Fabrikat Jiangsu Hengkang oder gleichwertig; Luftleistung 12.500 m³/h."],
            ["Abluftkanal", "Die Standardausstattung umfasst zwei gerade Kanalstücke und einen Rohrbogen."],
            ["Beleuchtungssystem", "Obere LED-Beleuchtung auf beiden Kabinenseiten. Die Leuchtenrahmen bestehen aus 0,6 mm starkem, verzinktem und pulverbeschichtetem Stahlblech. Umfang: 8 Einheiten × 4 Röhren = insgesamt 32 LED-Röhren mit jeweils 24 W."],
            ["Heizsystem", "Acht außen montierte, fest installierte Infrarot-Heizeinheiten mit jeweils 3 kW; Gesamtheizleistung 24 kW. Je vier Einheiten sind auf jeder Kabinenseite angeordnet."],
            ["Filtersystem", "Der Zuluft-Vorfilter erfasst Partikel größer als 10 µm. Das hocheffiziente Deckenfiltermedium SF-700G erfasst Partikel größer als 4 µm mit einem Abscheidegrad von mindestens 99 %. Im Bodenbereich wird ein Glasfaser-Filtermedium mittlerer Effizienz eingesetzt."],
            ["Elektrische Steuerung", "Elektrische Steuerungskomponenten von CHINT oder gleichwertig. Der Hauptstromkreis verfügt über Fehlerstrom-, Phasenausfall-, Kurzschluss- und Überlastschutz sowie eine Zeitsteuerung. Einstellbare Temperaturregelung mit Übertemperaturalarm."],
            ["Stromversorgung", "380 V / 220 V, 3-phasig, 4-Leiter, 50 Hz; Gesamtleistung ca. 35 kW."]
          ]
        }
      },
      "GBT-SB6900-E-PLUS": { status: "reserved" },
      "GBT-SB6900-E-PRO": { status: "reserved" },
      "GBT-SB6900-NG-ECO": { status: "reserved" },
      "GBT-SB6900-NG-PLUS": { status: "reserved" },
      "GBT-SB6900-NG-PRO": { status: "reserved" },
      "GBT-SB6900-D-ECO": { status: "reserved" },
      "GBT-SB6900-D-PLUS": { status: "reserved" },
      "GBT-SB6900-D-PRO": { status: "reserved" }
    }
  };
})();
